import os
import re
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from config import TEMP_DIR

# 🎨 1. ADVANCED PDF DESIGNER (Header & Footer on EVERY Page)
def add_header_footer(canvas, doc):
    canvas.saveState()
    
    # --- HEADER DESIGN ---
    canvas.setFillColor(colors.HexColor("#1A365D")) # Premium Dark Blue Background
    canvas.rect(0, 735, 612, 65, fill=1, stroke=0)
    
    # Header Main Title
    canvas.setFillColor(colors.white)
    canvas.setFont('Helvetica-Bold', 18)
    canvas.drawCentredString(306, 765, "Aditya's Elite AI - Premium Study Notes")
    
    # Header Subtitle
    canvas.setFillColor(colors.HexColor("#A0AEC0"))
    canvas.setFont('Helvetica-Oblique', 11)
    canvas.drawCentredString(306, 745, "Generated by Smart Vision Scanner")
    
    # --- FOOTER DESIGN ---
    canvas.setStrokeColor(colors.HexColor("#CBD5E0"))
    canvas.setLineWidth(1)
    canvas.line(40, 40, 572, 40) # Beautiful thin footer line
    
    canvas.setFillColor(colors.HexColor("#718096"))
    canvas.setFont('Helvetica', 9)
    canvas.drawCentredString(306, 25, f"Page {doc.page} | Engineered by Aditya | @aadit_paswan.007")
    
    canvas.restoreState()


# 🚀 2. THE ULTIMATE PDF GENERATOR FUNCTION
def generate_study_notes_pdf(user_id: int, topic: str, text_content: str) -> str:
    # 🧹 CLEANUP: Telegram Emojis crash PDF generators. Let's clean them automatically.
    # Keep some basic formatting characters if needed, but remove complex emojis.
    clean_text = re.sub(r'[^\x00-\x7F]+', ' ', text_content)
    clean_text = clean_text.replace('**', '') # Remove markdown asterisks
    
    if not os.path.exists(TEMP_DIR):
        os.makedirs(TEMP_DIR)
        
    file_path = os.path.join(TEMP_DIR, f"Elite_Notes_{user_id}_{int(os.getpid())}.pdf")
    
    # Setup Document with proper margins
    doc = SimpleDocTemplate(
        file_path,
        pagesize=letter,
        rightMargin=45, leftMargin=45, 
        topMargin=80, bottomMargin=55
    )

    styles = getSampleStyleSheet()
    
    # 💎 CUSTOM PRO-LEVEL TEXT STYLES (Improved for Spacing and Readability)
    title_style = ParagraphStyle(
        name='EliteTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=24,
        textColor=colors.HexColor('#2B6CB0'), # Premium Blue
        spaceAfter=20,
        alignment=TA_LEFT
    )

    body_style = ParagraphStyle(
        name='EliteBody',
        parent=styles['BodyText'],
        fontName='Helvetica',
        fontSize=11,
        leading=18,  # Increased line height for better readability
        textColor=colors.HexColor('#2D3748'),
        spaceAfter=12, # Space between paragraphs
        alignment=TA_JUSTIFY # Justified text looks more professional
    )
    
    subheading_style = ParagraphStyle(
        name='EliteSubheading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#E53E3E'), # Accent Red for subheadings
        spaceBefore=15,
        spaceAfter=10
    )
    
    bullet_style = ParagraphStyle(
        name='EliteBullet',
        parent=styles['BodyText'],
        fontName='Helvetica',
        fontSize=11,
        leading=16,
        textColor=colors.HexColor('#2D3748'),
        leftIndent=20, # Indent bullet points
        spaceAfter=8
    )

    story = []

    # Add Topic Name
    safe_topic = topic[:70] + "..." if len(topic) > 70 else topic
    story.append(Paragraph(f"Subject: {safe_topic}", title_style))
    story.append(Spacer(1, 10)) # Extra space after title
    
    # 🧠 SMART TEXT ALIGNMENT & FORMATTING (Handling Bullets & Paragraphs)
    current_list = []
    
    for line in clean_text.split('\n'):
        line = line.strip()
        if not line:
            # If there's an active list, add it to the story before a blank line
            if current_list:
                story.append(ListFlowable(current_list, bulletType='bullet', start='circle', leftIndent=15))
                current_list = []
            continue
            
        if line.startswith(('Page 1', 'Page 2', 'Page 3', 'Page 4', 'Page 5')):
            if current_list:
                story.append(ListFlowable(current_list, bulletType='bullet', start='circle', leftIndent=15))
                current_list = []
            story.append(Paragraph(line, subheading_style))
        elif line.startswith(('-', '*', '•')):
             # Handle bullet points
             # Clean the starting character
             bullet_text = line[1:].strip()
             current_list.append(ListItem(Paragraph(bullet_text, bullet_style)))
        elif line.startswith('Quick Summary'):
            if current_list:
                story.append(ListFlowable(current_list, bulletType='bullet', start='circle', leftIndent=15))
                current_list = []
            story.append(Spacer(1, 10))
            story.append(Paragraph(f"<b>{line}</b>", body_style))
        else:
            if current_list:
                story.append(ListFlowable(current_list, bulletType='bullet', start='circle', leftIndent=15))
                current_list = []
            # Bold detection (basic)
            if line.isupper() and len(line) > 10:
                 story.append(Paragraph(f"<b>{line}</b>", body_style))
            else:
                 story.append(Paragraph(line, body_style))

    # Add any remaining list items
    if current_list:
        story.append(ListFlowable(current_list, bulletType='bullet', start='circle', leftIndent=15))

    # Build the PDF with our custom Header & Footer attached to every page
    doc.build(story, onFirstPage=add_header_footer, onLaterPages=add_header_footer)
    return file_path


# 🛡️ 3. SAFE CLEANUP FUNCTION (CRITICAL FOR SERVER SAFETY)
def safe_cleanup(file_path: str):
    """
    Safely removes transient system files to mitigate runtime disk consumption.
    """
    try:
        if file_path and os.path.exists(file_path):
            os.remove(file_path)
    except Exception as e:
        print(f"Error executing storage sweep on {file_path}: {e}")
    
